services:
  postgres_db:
    image: postgres:16-alpine
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    ports:
      - "6543:5432"
    environment:
      POSTGRES_DB: portfolio
      POSTGRES_USER: portfolio
      POSTGRES_PASSWORD: portfolio
    labels:
      - "io.portfolio.create.name=portfolio"

volumes:
  postgres_db_data:
    driver: local
    labels:
      - "io.portfolio.create.name=portfolio"
