import { MigrationInterface, QueryRunner } from "typeorm";

export class Initial1786478844400 implements MigrationInterface {
    name = 'Initial1786478844400'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "education_asset" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "position" integer NOT NULL, "educationId" uuid NOT NULL, "assetId" uuid, CONSTRAINT "PK_cb8ba09f64bafe94411bd82741c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_23e48dd68432c095522c3a24de" ON "education_asset"  ("assetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ad6d13e55481fa7d34d34cab7e" ON "education_asset"  ("educationId") `);
        await queryRunner.query(`CREATE TABLE "education_translation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "languageCode" character varying NOT NULL, "school" character varying NOT NULL, "slug" character varying NOT NULL, "degree" character varying, "location" character varying, "baseId" uuid, CONSTRAINT "PK_a155241b5a6703531eea7a9ce14" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2c13d5aae185f3564cc91dda22" ON "education_translation"  ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_7d3f42dbc0939c1aa792b508d9" ON "education_translation"  ("baseId") `);
        await queryRunner.query(`CREATE TABLE "education" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "startDate" date NOT NULL, "endDate" date, "isPresent" boolean NOT NULL, "gpa" real, "featuredAssetId" uuid, CONSTRAINT "PK_bf3d38701b3030a8ad634d43bd6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_990db285d0c95e42bd78ceb8bc" ON "education"  ("featuredAssetId") `);
        await queryRunner.query(`CREATE TABLE "skill_asset" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "position" integer NOT NULL, "skillId" uuid NOT NULL, "assetId" uuid, CONSTRAINT "PK_f90a3498654e891e6e5dfcdfd53" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1b52b3b73a1e4eda029499924a" ON "skill_asset"  ("assetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ad4d17b23d8c729895f3a220ef" ON "skill_asset"  ("skillId") `);
        await queryRunner.query(`CREATE TABLE "skill_translation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "languageCode" character varying NOT NULL, "name" character varying NOT NULL, "slug" character varying NOT NULL, "baseId" uuid, CONSTRAINT "PK_4a1d921d43f2abea977aa434b5c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_911068f97b305618f762540c91" ON "skill_translation"  ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_8855c8b285af4bd0e0ccc4345d" ON "skill_translation"  ("baseId") `);
        await queryRunner.query(`CREATE TABLE "skill" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "isFeatured" boolean NOT NULL DEFAULT false, "category" character varying NOT NULL, "featuredAssetId" uuid, CONSTRAINT "PK_a0d33334424e64fb78dc3ce7196" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b892b227386b953fd1ec49f93e" ON "skill"  ("featuredAssetId") `);
        await queryRunner.query(`CREATE TABLE "project_asset" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "position" integer NOT NULL, "projectId" uuid NOT NULL, "assetId" uuid, CONSTRAINT "PK_f5e78d08e205519505b99ae03e4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4841a719a0b297969c7fd5661d" ON "project_asset"  ("assetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8ce4758846594ffc5643839653" ON "project_asset"  ("projectId") `);
        await queryRunner.query(`CREATE TABLE "project_translation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "languageCode" character varying NOT NULL, "name" character varying NOT NULL, "slug" character varying NOT NULL, "description" text NOT NULL, "overview" text NOT NULL, "features" text NOT NULL, "technicalHighlights" text NOT NULL, "contributions" text NOT NULL, "challengesAndSolutions" text NOT NULL, "techStack" text NOT NULL, "baseId" uuid, CONSTRAINT "PK_08fe426f8f10f6867cfccec3949" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5dff9dfa8b85b8bc95de44db8a" ON "project_translation"  ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_15c15a47f52ae54e8070a32951" ON "project_translation"  ("baseId") `);
        await queryRunner.query(`CREATE TABLE "project" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" date, "liveDemoUrl" character varying NOT NULL, "repoUrl" character varying NOT NULL, "enabled" boolean NOT NULL DEFAULT true, "finished" boolean NOT NULL, "featured" boolean NOT NULL DEFAULT false, "featuredAssetId" uuid, "careerId" uuid, "educationId" uuid, CONSTRAINT "PK_4d68b1358bb5b766d3e78f32f57" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2ee9d5da2276135e84f55c9337" ON "project"  ("featuredAssetId") `);
        await queryRunner.query(`CREATE TABLE "career_translation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "languageCode" character varying NOT NULL, "name" character varying NOT NULL, "slug" character varying NOT NULL, "location" character varying, "organization" character varying NOT NULL, "responsibilities" text NOT NULL, "impact" text NOT NULL, "learned" text NOT NULL, "baseId" uuid, CONSTRAINT "UQ_fd30896d26130654af4675c934b" UNIQUE ("slug"), CONSTRAINT "PK_158601fe83ad2855533602a0de2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_91acff23dd454a0b170d4ad4f8" ON "career_translation"  ("baseId") `);
        await queryRunner.query(`CREATE TABLE "career_asset" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "position" integer NOT NULL, "careerId" uuid NOT NULL, "assetId" uuid, CONSTRAINT "PK_25380f7f2a41c77b8350a56e3ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8ecfa6cbf5433b47c394854f12" ON "career_asset"  ("assetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c8876058e4113e8f0f8cc1824e" ON "career_asset"  ("careerId") `);
        await queryRunner.query(`CREATE TABLE "career" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "startDate" date NOT NULL, "endDate" date, "isPresent" boolean NOT NULL, "mode" character varying NOT NULL, "type" character varying NOT NULL, "featuredAssetId" uuid, CONSTRAINT "PK_5f694c0aa9babcae2c4ad61c7d0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_30d6b481f6c083cf46ab41cc09" ON "career"  ("featuredAssetId") `);
        await queryRunner.query(`CREATE TABLE "contact_method_asset" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "position" integer NOT NULL, "contactMethodId" uuid NOT NULL, "assetId" uuid, CONSTRAINT "PK_522be86b3043c94de43ec16f805" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f41e78e36f83faaa7aa02bfd70" ON "contact_method_asset"  ("assetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_04266d1e98086a263b393b5531" ON "contact_method_asset"  ("contactMethodId") `);
        await queryRunner.query(`CREATE TABLE "contact_method_translation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "languageCode" character varying NOT NULL, "name" character varying NOT NULL, "baseId" uuid, CONSTRAINT "PK_88772b7ede77ad7d2f8d55db6b1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9c37acebfb9d03871540f3c888" ON "contact_method_translation"  ("baseId") `);
        await queryRunner.query(`CREATE TABLE "contact_method" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "url" character varying NOT NULL, "copyableText" text, "featuredAssetId" uuid, CONSTRAINT "PK_ee65af2b1bc0c820a934549b8ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c52a1b74f55fcf06ea411a46c5" ON "contact_method"  ("featuredAssetId") `);
        await queryRunner.query(`CREATE TABLE "profile_asset" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "position" integer NOT NULL, "profileId" uuid NOT NULL, "assetId" uuid, CONSTRAINT "PK_f7dedea3f12d75c3c2008b0c557" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ff8d3ca9892624e8670cab30a4" ON "profile_asset"  ("assetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_970483b4c4f190b06a0ea1bf45" ON "profile_asset"  ("profileId") `);
        await queryRunner.query(`CREATE TABLE "profile_translation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "languageCode" character varying NOT NULL, "summary" text NOT NULL, "intro" character varying NOT NULL, "jobTitle" character varying NOT NULL, "location" character varying NOT NULL, "subHeading" character varying NOT NULL, "subtitle" character varying NOT NULL, "currentFocus" text NOT NULL, "displayName" character varying NOT NULL, "baseId" uuid, CONSTRAINT "PK_9fd76271a528a65b6ba414c1ec1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_812db3d81df2c572dd79599e17" ON "profile_translation"  ("baseId") `);
        await queryRunner.query(`CREATE TABLE "profile" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "projectsShipped" integer NOT NULL DEFAULT '0', "openSourceContributions" integer NOT NULL DEFAULT '0', "yearsOfExperience" integer NOT NULL DEFAULT '0', "handle" character varying NOT NULL, "username" character varying NOT NULL, "password" character varying NOT NULL, "token" character varying, "featuredAssetId" uuid, CONSTRAINT "PK_3dd8bfc97e4a77c70971591bdcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e030e28dffd0484ea9a6a1b586" ON "profile"  ("featuredAssetId") `);
        await queryRunner.query(`CREATE TABLE "tag" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "value" character varying NOT NULL, CONSTRAINT "PK_8e4052373c579afc1471f526760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "asset_translation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "languageCode" character varying NOT NULL, "name" character varying NOT NULL, "baseId" uuid, CONSTRAINT "PK_2f22e63eefeef14d245bdb956b6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4eed4464adef51f53e1c7d8021" ON "asset_translation"  ("baseId") `);
        await queryRunner.query(`CREATE TABLE "asset" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "mimetype" character varying NOT NULL, "type" character varying NOT NULL, "sourceFileKey" character varying NOT NULL, "previewFileKey" character varying NOT NULL, "width" integer NOT NULL DEFAULT '0', "height" integer NOT NULL DEFAULT '0', "fileSize" integer NOT NULL, "sourceIdentifier" character varying NOT NULL, "previewIdentifier" character varying NOT NULL, CONSTRAINT "PK_1209d107fe21482beaea51b745e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "achievement_asset" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "position" integer NOT NULL, "achievementId" uuid NOT NULL, "assetId" uuid, CONSTRAINT "PK_d0edae866730dcc694e70466337" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d85e73fca60d94fcf9ec47406e" ON "achievement_asset"  ("assetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7ff1bf164c00cc8ca299bda5e1" ON "achievement_asset"  ("achievementId") `);
        await queryRunner.query(`CREATE TABLE "achievement_translation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "languageCode" character varying NOT NULL, "name" character varying NOT NULL, "slug" character varying NOT NULL, "organization" character varying NOT NULL, "baseId" uuid, CONSTRAINT "PK_89db1f72d859d6ace932f607ea1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1c19ec76e869a8a991cb28431d" ON "achievement_translation"  ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_f03b29f65056947c07b077c00a" ON "achievement_translation"  ("baseId") `);
        await queryRunner.query(`CREATE TABLE "achievement" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "type" character varying NOT NULL, "issueDate" date NOT NULL, "credentialUrl" character varying NOT NULL, "featuredAssetId" uuid, "careerId" uuid, CONSTRAINT "PK_441339f40e8ce717525a381671e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_890633771c8d37af6954fb82fd" ON "achievement"  ("featuredAssetId") `);
        await queryRunner.query(`CREATE TABLE "project_skills_skill" ("projectId" uuid NOT NULL, "skillId" uuid NOT NULL, CONSTRAINT "PK_75331efa833de97a3674c5152e8" PRIMARY KEY ("projectId", "skillId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d3434af0018f24c564c2ab1fbf" ON "project_skills_skill"  ("projectId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8650b9852e80554b1f0d493ac5" ON "project_skills_skill"  ("skillId") `);
        await queryRunner.query(`CREATE TABLE "project_achievements_achievement" ("projectId" uuid NOT NULL, "achievementId" uuid NOT NULL, CONSTRAINT "PK_13a9e1e96c3a06570013fdc2c63" PRIMARY KEY ("projectId", "achievementId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b82686f07b3a0f1afad74c67e4" ON "project_achievements_achievement"  ("projectId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f45b8d8232b5f5edb7ccc2b3fa" ON "project_achievements_achievement"  ("achievementId") `);
        await queryRunner.query(`CREATE TABLE "asset_tags_tag" ("assetId" uuid NOT NULL, "tagId" uuid NOT NULL, CONSTRAINT "PK_c4113b84381e953901fa5553654" PRIMARY KEY ("assetId", "tagId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9e412b00d4c6cee1a4b3d92071" ON "asset_tags_tag"  ("assetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_fb5e800171ffbe9823f2cc727f" ON "asset_tags_tag"  ("tagId") `);
        await queryRunner.query(`ALTER TABLE "education_asset" ADD CONSTRAINT "FK_23e48dd68432c095522c3a24de8" FOREIGN KEY ("assetId") REFERENCES "asset"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "education_asset" ADD CONSTRAINT "FK_ad6d13e55481fa7d34d34cab7e7" FOREIGN KEY ("educationId") REFERENCES "education"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "education_translation" ADD CONSTRAINT "FK_7d3f42dbc0939c1aa792b508d9a" FOREIGN KEY ("baseId") REFERENCES "education"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "education" ADD CONSTRAINT "FK_990db285d0c95e42bd78ceb8bc4" FOREIGN KEY ("featuredAssetId") REFERENCES "asset"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "skill_asset" ADD CONSTRAINT "FK_1b52b3b73a1e4eda029499924a6" FOREIGN KEY ("assetId") REFERENCES "asset"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "skill_asset" ADD CONSTRAINT "FK_ad4d17b23d8c729895f3a220efa" FOREIGN KEY ("skillId") REFERENCES "skill"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "skill_translation" ADD CONSTRAINT "FK_8855c8b285af4bd0e0ccc4345d5" FOREIGN KEY ("baseId") REFERENCES "skill"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "skill" ADD CONSTRAINT "FK_b892b227386b953fd1ec49f93e9" FOREIGN KEY ("featuredAssetId") REFERENCES "asset"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_asset" ADD CONSTRAINT "FK_4841a719a0b297969c7fd5661db" FOREIGN KEY ("assetId") REFERENCES "asset"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_asset" ADD CONSTRAINT "FK_8ce4758846594ffc5643839653e" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_translation" ADD CONSTRAINT "FK_15c15a47f52ae54e8070a32951e" FOREIGN KEY ("baseId") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project" ADD CONSTRAINT "FK_2ee9d5da2276135e84f55c93378" FOREIGN KEY ("featuredAssetId") REFERENCES "asset"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project" ADD CONSTRAINT "FK_638174fd5f3847f4d5a41de710b" FOREIGN KEY ("careerId") REFERENCES "career"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project" ADD CONSTRAINT "FK_ee9b667a041a86bb199d26bd9db" FOREIGN KEY ("educationId") REFERENCES "education"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "career_translation" ADD CONSTRAINT "FK_91acff23dd454a0b170d4ad4f82" FOREIGN KEY ("baseId") REFERENCES "career"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "career_asset" ADD CONSTRAINT "FK_8ecfa6cbf5433b47c394854f123" FOREIGN KEY ("assetId") REFERENCES "asset"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "career_asset" ADD CONSTRAINT "FK_c8876058e4113e8f0f8cc1824e1" FOREIGN KEY ("careerId") REFERENCES "career"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "career" ADD CONSTRAINT "FK_30d6b481f6c083cf46ab41cc09d" FOREIGN KEY ("featuredAssetId") REFERENCES "asset"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contact_method_asset" ADD CONSTRAINT "FK_f41e78e36f83faaa7aa02bfd703" FOREIGN KEY ("assetId") REFERENCES "asset"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contact_method_asset" ADD CONSTRAINT "FK_04266d1e98086a263b393b55315" FOREIGN KEY ("contactMethodId") REFERENCES "contact_method"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contact_method_translation" ADD CONSTRAINT "FK_9c37acebfb9d03871540f3c888a" FOREIGN KEY ("baseId") REFERENCES "contact_method"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contact_method" ADD CONSTRAINT "FK_c52a1b74f55fcf06ea411a46c51" FOREIGN KEY ("featuredAssetId") REFERENCES "asset"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "profile_asset" ADD CONSTRAINT "FK_ff8d3ca9892624e8670cab30a49" FOREIGN KEY ("assetId") REFERENCES "asset"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "profile_asset" ADD CONSTRAINT "FK_970483b4c4f190b06a0ea1bf45c" FOREIGN KEY ("profileId") REFERENCES "profile"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "profile_translation" ADD CONSTRAINT "FK_812db3d81df2c572dd79599e172" FOREIGN KEY ("baseId") REFERENCES "profile"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "profile" ADD CONSTRAINT "FK_e030e28dffd0484ea9a6a1b586e" FOREIGN KEY ("featuredAssetId") REFERENCES "asset"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset_translation" ADD CONSTRAINT "FK_4eed4464adef51f53e1c7d80212" FOREIGN KEY ("baseId") REFERENCES "asset"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "achievement_asset" ADD CONSTRAINT "FK_d85e73fca60d94fcf9ec47406ee" FOREIGN KEY ("assetId") REFERENCES "asset"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "achievement_asset" ADD CONSTRAINT "FK_7ff1bf164c00cc8ca299bda5e1a" FOREIGN KEY ("achievementId") REFERENCES "achievement"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "achievement_translation" ADD CONSTRAINT "FK_f03b29f65056947c07b077c00ad" FOREIGN KEY ("baseId") REFERENCES "achievement"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "achievement" ADD CONSTRAINT "FK_890633771c8d37af6954fb82fde" FOREIGN KEY ("featuredAssetId") REFERENCES "asset"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "achievement" ADD CONSTRAINT "FK_5ecea8e22ed92dd6a1da055feca" FOREIGN KEY ("careerId") REFERENCES "career"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_skills_skill" ADD CONSTRAINT "FK_d3434af0018f24c564c2ab1fbfe" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "project_skills_skill" ADD CONSTRAINT "FK_8650b9852e80554b1f0d493ac59" FOREIGN KEY ("skillId") REFERENCES "skill"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_achievements_achievement" ADD CONSTRAINT "FK_b82686f07b3a0f1afad74c67e4c" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "project_achievements_achievement" ADD CONSTRAINT "FK_f45b8d8232b5f5edb7ccc2b3faf" FOREIGN KEY ("achievementId") REFERENCES "achievement"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset_tags_tag" ADD CONSTRAINT "FK_9e412b00d4c6cee1a4b3d920716" FOREIGN KEY ("assetId") REFERENCES "asset"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "asset_tags_tag" ADD CONSTRAINT "FK_fb5e800171ffbe9823f2cc727fd" FOREIGN KEY ("tagId") REFERENCES "tag"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "asset_tags_tag" DROP CONSTRAINT "FK_fb5e800171ffbe9823f2cc727fd"`);
        await queryRunner.query(`ALTER TABLE "asset_tags_tag" DROP CONSTRAINT "FK_9e412b00d4c6cee1a4b3d920716"`);
        await queryRunner.query(`ALTER TABLE "project_achievements_achievement" DROP CONSTRAINT "FK_f45b8d8232b5f5edb7ccc2b3faf"`);
        await queryRunner.query(`ALTER TABLE "project_achievements_achievement" DROP CONSTRAINT "FK_b82686f07b3a0f1afad74c67e4c"`);
        await queryRunner.query(`ALTER TABLE "project_skills_skill" DROP CONSTRAINT "FK_8650b9852e80554b1f0d493ac59"`);
        await queryRunner.query(`ALTER TABLE "project_skills_skill" DROP CONSTRAINT "FK_d3434af0018f24c564c2ab1fbfe"`);
        await queryRunner.query(`ALTER TABLE "achievement" DROP CONSTRAINT "FK_5ecea8e22ed92dd6a1da055feca"`);
        await queryRunner.query(`ALTER TABLE "achievement" DROP CONSTRAINT "FK_890633771c8d37af6954fb82fde"`);
        await queryRunner.query(`ALTER TABLE "achievement_translation" DROP CONSTRAINT "FK_f03b29f65056947c07b077c00ad"`);
        await queryRunner.query(`ALTER TABLE "achievement_asset" DROP CONSTRAINT "FK_7ff1bf164c00cc8ca299bda5e1a"`);
        await queryRunner.query(`ALTER TABLE "achievement_asset" DROP CONSTRAINT "FK_d85e73fca60d94fcf9ec47406ee"`);
        await queryRunner.query(`ALTER TABLE "asset_translation" DROP CONSTRAINT "FK_4eed4464adef51f53e1c7d80212"`);
        await queryRunner.query(`ALTER TABLE "profile" DROP CONSTRAINT "FK_e030e28dffd0484ea9a6a1b586e"`);
        await queryRunner.query(`ALTER TABLE "profile_translation" DROP CONSTRAINT "FK_812db3d81df2c572dd79599e172"`);
        await queryRunner.query(`ALTER TABLE "profile_asset" DROP CONSTRAINT "FK_970483b4c4f190b06a0ea1bf45c"`);
        await queryRunner.query(`ALTER TABLE "profile_asset" DROP CONSTRAINT "FK_ff8d3ca9892624e8670cab30a49"`);
        await queryRunner.query(`ALTER TABLE "contact_method" DROP CONSTRAINT "FK_c52a1b74f55fcf06ea411a46c51"`);
        await queryRunner.query(`ALTER TABLE "contact_method_translation" DROP CONSTRAINT "FK_9c37acebfb9d03871540f3c888a"`);
        await queryRunner.query(`ALTER TABLE "contact_method_asset" DROP CONSTRAINT "FK_04266d1e98086a263b393b55315"`);
        await queryRunner.query(`ALTER TABLE "contact_method_asset" DROP CONSTRAINT "FK_f41e78e36f83faaa7aa02bfd703"`);
        await queryRunner.query(`ALTER TABLE "career" DROP CONSTRAINT "FK_30d6b481f6c083cf46ab41cc09d"`);
        await queryRunner.query(`ALTER TABLE "career_asset" DROP CONSTRAINT "FK_c8876058e4113e8f0f8cc1824e1"`);
        await queryRunner.query(`ALTER TABLE "career_asset" DROP CONSTRAINT "FK_8ecfa6cbf5433b47c394854f123"`);
        await queryRunner.query(`ALTER TABLE "career_translation" DROP CONSTRAINT "FK_91acff23dd454a0b170d4ad4f82"`);
        await queryRunner.query(`ALTER TABLE "project" DROP CONSTRAINT "FK_ee9b667a041a86bb199d26bd9db"`);
        await queryRunner.query(`ALTER TABLE "project" DROP CONSTRAINT "FK_638174fd5f3847f4d5a41de710b"`);
        await queryRunner.query(`ALTER TABLE "project" DROP CONSTRAINT "FK_2ee9d5da2276135e84f55c93378"`);
        await queryRunner.query(`ALTER TABLE "project_translation" DROP CONSTRAINT "FK_15c15a47f52ae54e8070a32951e"`);
        await queryRunner.query(`ALTER TABLE "project_asset" DROP CONSTRAINT "FK_8ce4758846594ffc5643839653e"`);
        await queryRunner.query(`ALTER TABLE "project_asset" DROP CONSTRAINT "FK_4841a719a0b297969c7fd5661db"`);
        await queryRunner.query(`ALTER TABLE "skill" DROP CONSTRAINT "FK_b892b227386b953fd1ec49f93e9"`);
        await queryRunner.query(`ALTER TABLE "skill_translation" DROP CONSTRAINT "FK_8855c8b285af4bd0e0ccc4345d5"`);
        await queryRunner.query(`ALTER TABLE "skill_asset" DROP CONSTRAINT "FK_ad4d17b23d8c729895f3a220efa"`);
        await queryRunner.query(`ALTER TABLE "skill_asset" DROP CONSTRAINT "FK_1b52b3b73a1e4eda029499924a6"`);
        await queryRunner.query(`ALTER TABLE "education" DROP CONSTRAINT "FK_990db285d0c95e42bd78ceb8bc4"`);
        await queryRunner.query(`ALTER TABLE "education_translation" DROP CONSTRAINT "FK_7d3f42dbc0939c1aa792b508d9a"`);
        await queryRunner.query(`ALTER TABLE "education_asset" DROP CONSTRAINT "FK_ad6d13e55481fa7d34d34cab7e7"`);
        await queryRunner.query(`ALTER TABLE "education_asset" DROP CONSTRAINT "FK_23e48dd68432c095522c3a24de8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fb5e800171ffbe9823f2cc727f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9e412b00d4c6cee1a4b3d92071"`);
        await queryRunner.query(`DROP TABLE "asset_tags_tag"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f45b8d8232b5f5edb7ccc2b3fa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b82686f07b3a0f1afad74c67e4"`);
        await queryRunner.query(`DROP TABLE "project_achievements_achievement"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8650b9852e80554b1f0d493ac5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d3434af0018f24c564c2ab1fbf"`);
        await queryRunner.query(`DROP TABLE "project_skills_skill"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_890633771c8d37af6954fb82fd"`);
        await queryRunner.query(`DROP TABLE "achievement"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f03b29f65056947c07b077c00a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1c19ec76e869a8a991cb28431d"`);
        await queryRunner.query(`DROP TABLE "achievement_translation"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7ff1bf164c00cc8ca299bda5e1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d85e73fca60d94fcf9ec47406e"`);
        await queryRunner.query(`DROP TABLE "achievement_asset"`);
        await queryRunner.query(`DROP TABLE "asset"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4eed4464adef51f53e1c7d8021"`);
        await queryRunner.query(`DROP TABLE "asset_translation"`);
        await queryRunner.query(`DROP TABLE "tag"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e030e28dffd0484ea9a6a1b586"`);
        await queryRunner.query(`DROP TABLE "profile"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_812db3d81df2c572dd79599e17"`);
        await queryRunner.query(`DROP TABLE "profile_translation"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_970483b4c4f190b06a0ea1bf45"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ff8d3ca9892624e8670cab30a4"`);
        await queryRunner.query(`DROP TABLE "profile_asset"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c52a1b74f55fcf06ea411a46c5"`);
        await queryRunner.query(`DROP TABLE "contact_method"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c37acebfb9d03871540f3c888"`);
        await queryRunner.query(`DROP TABLE "contact_method_translation"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_04266d1e98086a263b393b5531"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f41e78e36f83faaa7aa02bfd70"`);
        await queryRunner.query(`DROP TABLE "contact_method_asset"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_30d6b481f6c083cf46ab41cc09"`);
        await queryRunner.query(`DROP TABLE "career"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c8876058e4113e8f0f8cc1824e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8ecfa6cbf5433b47c394854f12"`);
        await queryRunner.query(`DROP TABLE "career_asset"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_91acff23dd454a0b170d4ad4f8"`);
        await queryRunner.query(`DROP TABLE "career_translation"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2ee9d5da2276135e84f55c9337"`);
        await queryRunner.query(`DROP TABLE "project"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_15c15a47f52ae54e8070a32951"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5dff9dfa8b85b8bc95de44db8a"`);
        await queryRunner.query(`DROP TABLE "project_translation"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8ce4758846594ffc5643839653"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4841a719a0b297969c7fd5661d"`);
        await queryRunner.query(`DROP TABLE "project_asset"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b892b227386b953fd1ec49f93e"`);
        await queryRunner.query(`DROP TABLE "skill"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8855c8b285af4bd0e0ccc4345d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_911068f97b305618f762540c91"`);
        await queryRunner.query(`DROP TABLE "skill_translation"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad4d17b23d8c729895f3a220ef"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1b52b3b73a1e4eda029499924a"`);
        await queryRunner.query(`DROP TABLE "skill_asset"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_990db285d0c95e42bd78ceb8bc"`);
        await queryRunner.query(`DROP TABLE "education"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7d3f42dbc0939c1aa792b508d9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2c13d5aae185f3564cc91dda22"`);
        await queryRunner.query(`DROP TABLE "education_translation"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad6d13e55481fa7d34d34cab7e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_23e48dd68432c095522c3a24de"`);
        await queryRunner.query(`DROP TABLE "education_asset"`);
    }

}
