import type { Metadata } from "next";
import { IBM_Plex_Sans, IBM_Plex_Sans_Arabic } from "next/font/google";
import "./globals.css";
import "reflect-metadata";
import { Analytics } from "@vercel/analytics/next";
import { notFound } from "next/navigation";
import { I18nProvider } from "@/components/providers/i18n-provider";
import { QueryClientProvider } from "@/components/providers/query-client-provider";
import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { sharedConfig } from "@/lib/config/shared-config";
import type { LanguageCode } from "@/lib/dto/language-code";
import { isRtl } from "@/lib/helpers/locale-utils";
import { cn } from "@/lib/utils";

const ibmPlexSans = IBM_Plex_Sans({
  variable: "--font-ibm-plex-sans",
  subsets: ["latin"],
});

const ibmPlexSansAr = IBM_Plex_Sans_Arabic({
  variable: "--font-ibm-plex-sans-ar",
  subsets: ["arabic", "latin"],
  weight: ["200", "400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: LayoutProps<"/[locale]">) {
  const { locale } = await params;

  const typedLocale = locale as LanguageCode;

  // if (!sharedConfig.i18n.locales.some((l) => l.key === locale)) {
  //   return notFound();
  // }

  return (
    <html
      lang={typedLocale}
      dir={isRtl(typedLocale) ? "rtl" : "ltr"}
      className={cn(
        "h-full antialiased",
        isRtl(typedLocale) ? ibmPlexSansAr.variable : ibmPlexSans.variable,
      )}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (() => {
                if (typeof window !== 'undefined'){
                  const accentColor = localStorage.getItem("accent-color");
  
                  if (accentColor) {
                    document.documentElement.classList.add(accentColor);
                  }
                }
              })();
            `,
          }}
          suppressHydrationWarning
        />
        <Toaster />
        <QueryClientProvider>
          <I18nProvider locale={locale}>
            <TooltipProvider>{children}</TooltipProvider>
          </I18nProvider>
        </QueryClientProvider>
        <Analytics />
      </body>
    </html>
  );
}
